{
 "title": "Smart Home IoT",
 "tags": [ "smarthome" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bedroom Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bedroom_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Bedroom Light",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bedroom_light\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Livingroom Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"livingroom_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Livingroom Light",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"livingroom_light\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  }
 ]
}